#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://103.113.204.38:20005/hero_construction?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Pacific/Auckland
#    driver-class-name: com.mysql.jdbc.Driver
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 103.113.204.38:20000
#
#  application:
#    name: heroa-webs
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 8200

