spring:
  cloud:
    gateway:
      routes:
        - id: dreport_route
          uri: lb://heroa-dreport
          predicates:
            - Path=/api/dreport/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://heroa-renren
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
